version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # do some linting (because we don't have tests yet ;--;)
      - run:
          name: lint and build
          command: |
            npm run lint
            npm run build

      # make the built addon downloadable from CI
      - store_artifacts:
          path: ~/repo/web-ext-artifacts
